# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10helloworld.proto\x12\nhelloworld\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1a\n\tIntNumber\x12\r\n\x05value\x18\x01 \x01(\x05\"\x1c\n\x0b\x46loatNumber\x12\r\n\x05value\x18\x01 \x01(\x02\x32\xd7\x01\n\x07Greeter\x12>\n\x08SayHello\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReply\"\x00\x12\x41\n\x0b\x43omputeMean\x12\x15.helloworld.IntNumber\x1a\x17.helloworld.FloatNumber\"\x00(\x01\x12I\n\x11\x43omputeMeanStream\x12\x15.helloworld.IntNumber\x1a\x17.helloworld.FloatNumber\"\x00(\x01\x30\x01\x42\rZ\x0b./go_clientb\x06proto3')



_HELLOREQUEST = DESCRIPTOR.message_types_by_name['HelloRequest']
_HELLOREPLY = DESCRIPTOR.message_types_by_name['HelloReply']
_INTNUMBER = DESCRIPTOR.message_types_by_name['IntNumber']
_FLOATNUMBER = DESCRIPTOR.message_types_by_name['FloatNumber']
HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

IntNumber = _reflection.GeneratedProtocolMessageType('IntNumber', (_message.Message,), {
  'DESCRIPTOR' : _INTNUMBER,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.IntNumber)
  })
_sym_db.RegisterMessage(IntNumber)

FloatNumber = _reflection.GeneratedProtocolMessageType('FloatNumber', (_message.Message,), {
  'DESCRIPTOR' : _FLOATNUMBER,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.FloatNumber)
  })
_sym_db.RegisterMessage(FloatNumber)

_GREETER = DESCRIPTOR.services_by_name['Greeter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\013./go_client'
  _HELLOREQUEST._serialized_start=32
  _HELLOREQUEST._serialized_end=60
  _HELLOREPLY._serialized_start=62
  _HELLOREPLY._serialized_end=91
  _INTNUMBER._serialized_start=93
  _INTNUMBER._serialized_end=119
  _FLOATNUMBER._serialized_start=121
  _FLOATNUMBER._serialized_end=149
  _GREETER._serialized_start=152
  _GREETER._serialized_end=367
# @@protoc_insertion_point(module_scope)
